### ISSUE TITLE
It is a question, not issue

### ISSUE THREAD

**Issue by 461353349** [chuhuaxian/OVM#1]
Is MeshViewer opensource also?
What is the difference between OpenVolumeMesh and OVM?

**Comment by chuhuaxian** [comment]
Not yet.
But if you are a Chinese student and your supervisor knows me, you may ask
your supervisor to email me.

Thank you.

Best,

Chuhua Xian

School of Computer Science and Engineering,
South China University of Technology

461353349 <notifications@github.com> 于2019年12月20日周五 上午10:26写道：

**Comment by 461353349** [comment]
Thanks.
